services:
  app:
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

  postgres:
    image: postgres:16

    container_name: postgres_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
       - "5432:5432"

    volumes:
        - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: