name: Spring Boot CI

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: Gestion_equipos_DB
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres -d Gestion_equipos_DB"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission
        run: chmod +x mvnw

      - name: Verify PostgreSQL
        env:
          PGPASSWORD: postgres
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          pg_isready -h localhost -p 5432 -U postgres -d Gestion_equipos_DB
          psql -h localhost -p 5432 -U postgres -d Gestion_equipos_DB -c "select 1;"

      - name: Verify environment variables
        env:
          DB_URL: jdbc:postgresql://localhost:5432/Gestion_equipos_DB
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          JWT_SECRET: "test-jwt-secret-key-12345678901234567890"
          JWT_EXPIRATION: "3600000"
        run: |
          echo "DB_URL=$DB_URL"
          echo "DB_USERNAME=$DB_USERNAME"
      
          if [ -n "$DB_PASSWORD" ]; then
            echo "DB_PASSWORD OK"
          else
            echo "DB_PASSWORD EMPTY"
          fi
      
          if [ -n "$JWT_SECRET" ]; then
            echo "JWT_SECRET OK"
          else
            echo "JWT_SECRET EMPTY"
          fi


      - name: Run tests
        env:
          DB_URL: jdbc:postgresql://localhost:5432/Gestion_equipos_DB
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          JWT_SECRET: "test-jwt-secret-key-12345678901234567890"
          JWT_EXPIRATION: "3600000"
          JWT_REFRESH_EXPIRATION: "604800000"
        run: ./mvnw test -e

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports
            target/*.log

